version: "3.9"

services:

    docker-db:
        image: mysql
        container_name: docker-db
        environment:
            MYSQL_USER: docker
            MYSQL_ROOT_PASSWORD: password
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: quiz_app
        volumes:
            - ../storage/dbdata:/var/lib/mysql
            - $GOPATH/pkg/mod/cache:/go/pkg/mod/cache
        ports:
            - "3106:3306"
        networks:
            - application

    quiz-app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: quiz-app
        working_dir: /app
        tty: true
        stdin_open: true
        restart: unless-stopped
        environment:
            APP_ENV: production
        volumes:
            - ../:/app
        ports:
            - "3000:1323"
        networks:
            - application
        depends_on:
            - docker-db

networks:
    application:
        name: application
        driver: bridge
